name: Github Actions Basics

on:
  push:
    branches: [main]

jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Identity
        run: |
           git config --global user.email "ilonakot92@gmail.com"
           git config --global user.name "psycho0sis"
      - name: Update version of Clever Shop!
        run: |
          npm version major
          git push --follow-tags
